### PR TITLE
Included categories in csv template

### PR DESCRIPTION
**Pull request by MiletaStanisic**
https://app.asana.com/0/503101155812087/1150144464345003/f
https://app.asana.com/0/1135320259326480/1153663021922931

### CODE REVIEW

**Comment by najiatallah** [comment]
https://app.asana.com/0/503101155812087/1150144464345003/f

**Comment by najiatallah** [comment]
Approved

**Comment by najiatallah** [comment]
Approved

**Comment by MiletaStanisic** [comment]
Ticket for latest changes: https://app.asana.com/0/1135320259326480/1153663021922931

**Pull request merged**
