### PR TITLE
fixed breadcrumb, query and deep link

### PR DESCRIPTION
**Pull request by NenoR96**
https://app.asana.com/0/1135320259326480/1155915230605841/
https://app.asana.com/0/1135320259326480/1158810551305353/f

### CODE REVIEW

**Comment by mikailbayram** [comment]
Approved

**Comment by najiatallah** [comment]
Approved

**Comment by mikailbayram** [comment]
This PR includes PR #69

**Comment by najiatallah** [comment]
Approved

**Pull request merged**
